/* Generated by Yosys 0.10.0 (git sha1 dca8fb54a, gcc 7.5.0-3ubuntu1~18.04 -fPIC -Os) */

module counter(clk, rst, \q[0] , \q[1] , \q[2] , \q[3] , \q[4] , \q[5] , \q[6] , \q[7] );
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  input clk;
  wire n22;
  wire n26;
  wire n30;
  wire n34;
  wire n38;
  wire n42;
  wire n46;
  wire n50;
  output \q[0] ;
  reg \q[0] ;
  output \q[1] ;
  reg \q[1] ;
  output \q[2] ;
  reg \q[2] ;
  output \q[3] ;
  reg \q[3] ;
  output \q[4] ;
  reg \q[4] ;
  output \q[5] ;
  reg \q[5] ;
  output \q[6] ;
  reg \q[6] ;
  output \q[7] ;
  reg \q[7] ;
  input rst;
  always @(posedge clk)
    \q[5]  <= n22;
  always @(posedge clk)
    \q[6]  <= n26;
  always @(posedge clk)
    \q[7]  <= n30;
  always @(posedge clk)
    \q[0]  <= n34;
  always @(posedge clk)
    \q[1]  <= n38;
  always @(posedge clk)
    \q[2]  <= n42;
  always @(posedge clk)
    \q[3]  <= n46;
  always @(posedge clk)
    \q[4]  <= n50;
  assign n38 = 8'h14 >> { \q[0] , \q[1] , rst };
  assign n42 = 16'h0708 >> { \q[2] , rst, \q[0] , \q[1]  };
  assign n46 = 8'h14 >> { _00_, \q[3] , rst };
  assign _00_ = 8'h80 >> { \q[0] , \q[1] , \q[2]  };
  assign n50 = 8'h14 >> { _01_, \q[4] , rst };
  assign _01_ = 16'h8000 >> { \q[0] , \q[1] , \q[2] , \q[3]  };
  assign n22 = 16'h0708 >> { \q[5] , rst, _01_, \q[4]  };
  assign n26 = 8'h14 >> { _02_, \q[6] , rst };
  assign _02_ = 8'h80 >> { _01_, \q[4] , \q[5]  };
  assign n30 = 8'h14 >> { _03_, \q[7] , rst };
  assign _03_ = 16'h8000 >> { _01_, \q[4] , \q[5] , \q[6]  };
  assign n34 = 4'h1 >> { rst, \q[0]  };
endmodule
